version: '3.8'

services:
  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/app_fast
    networks:
      private-net:
        aliases:
          - local.fast-api
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6565
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    networks:
      private-net:
        aliases:
          - local.fast-db

networks:
  private-net:
    external: true
