version: '3.8'

services:
  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/app_fast
    networks:
      private-net:
        aliases:
          - local.fast-api
    depends_on:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fastapi-docker-postgres
    ports:
      - "5432:5432"
    networks:
      private-net:
        aliases:
          - local.fast-db

networks:
  private-net:
    external: true
