version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - '8000:8000'
    volumes:
      - .:/app_fast
    networks:
      private-net:
        aliases:
          - local.fast-api
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fastapi-docker-postgres
    ports:
      - "5432:5432"
    networks:
      private-net:
        aliases:
          - local.fast-db

networks:
  private-net:
    external: true
